"""Add original_job_number and deleted job indexes

Revision ID: d0694454d94b
Revises: add_deleted_jobs_schema
Create Date: 2025-05-28 19:09:22.691954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0694454d94b'
down_revision = 'add_deleted_jobs_schema'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    insp = sa.inspect(bind)

    def has_table(name: str) -> bool:
        try:
            return name in insp.get_table_names()
        except Exception:
            return False

    def has_column(table: str, col: str) -> bool:
        try:
            return any(c["name"] == col for c in insp.get_columns(table))
        except Exception:
            return False

    # Create 'users' table if it doesn't exist
    if not has_table("users"):
        op.create_table(
            'users',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('username', sa.String(length=50), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('password', sa.String(length=255), nullable=False),
            sa.Column('role', sa.String(length=20), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('last_login', sa.DateTime(), nullable=True),
            sa.Column('last_ip', sa.String(length=45), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('username')
        )

    # Create 'fieldwork' if missing
    if not has_table("fieldwork"):
        op.create_table(
            'fieldwork',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('job_id', sa.Integer(), nullable=False),
            sa.Column('work_date', sa.Date(), nullable=False),
            sa.Column('start_time', sa.Time(), nullable=False),
            sa.Column('end_time', sa.Time(), nullable=False),
            sa.Column('total_time', sa.Float(), nullable=False),
            sa.Column('crew', sa.String(length=100), nullable=True),
            sa.Column('drone_card', sa.String(length=100), nullable=True),
            sa.Column('notes', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['job_id'], ['jobs.id']),
            sa.PrimaryKeyConstraint('id')
        )

    # Drop legacy tables if they exist
    for legacy in ("user", "related_jobs", "field_work"):
        if has_table(legacy):
            try:
                op.drop_table(legacy)
            except Exception:
                pass

    # Loosely attempt to update jobs table; ignore if not applicable
    try:
        with op.batch_alter_table('jobs', schema=None) as batch_op:
            # Only perform minimal, safe alterations
            if not has_column('jobs', 'updated_at'):
                batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

            # Ensure FKs point to users table
            try:
                batch_op.drop_constraint('jobs_deleted_by_id_fkey', type_='foreignkey')
            except Exception:
                pass
            try:
                batch_op.drop_constraint('jobs_created_by_id_fkey', type_='foreignkey')
            except Exception:
                pass
            try:
                batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'])
                batch_op.create_foreign_key(None, 'users', ['deleted_by_id'], ['id'])
            except Exception:
                pass
    except Exception:
        # If any of the above isn't applicable to the live schema, continue
        pass

    # Make tags table compatible if in legacy state (title -> name)
    if has_table('tags') and has_column('tags', 'title') and not has_column('tags', 'name'):
        with op.batch_alter_table('tags', schema=None) as batch_op:
            batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))
        op.execute(sa.text("UPDATE tags SET name = title WHERE name IS NULL"))
        with op.batch_alter_table('tags', schema=None) as batch_op:
            try:
                batch_op.drop_constraint('tags_title_key', type_='unique')
            except Exception:
                pass
            batch_op.create_unique_constraint(None, ['name'])
            batch_op.alter_column('name', nullable=False)
            batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
            batch_op.drop_column('title')

    # end of relaxed, idempotent upgrade


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('tags_title_key', ['title'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('color')
        batch_op.drop_column('name')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('jobs_created_by_id_fkey', 'user', ['created_by_id'], ['id'])
        batch_op.create_foreign_key('jobs_deleted_by_id_fkey', 'user', ['deleted_by_id'], ['id'])
        batch_op.create_index('idx_jobs_status', ['status'], unique=False, postgresql_where='(deleted_at IS NULL)')
        batch_op.create_index('idx_jobs_search_composite', ['deleted_at', 'status', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(deleted_at IS NULL)')
        batch_op.create_index('idx_jobs_job_number_trgm', ['job_number'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_jobs_job_number_prefix', ['job_number'], unique=False, postgresql_where='(deleted_at IS NULL)')
        batch_op.create_index('idx_jobs_job_number_lower', [sa.literal_column('lower(job_number::text)')], unique=False)
        batch_op.create_index('idx_jobs_job_number_clean', [sa.literal_column("regexp_replace(lower(job_number::text), '[^a-z0-9]'::text, ''::text, 'g'::text)")], unique=False)
        batch_op.create_index('idx_jobs_deleted_lookup', ['original_job_number', 'deleted_at'], unique=False)
        batch_op.create_index('idx_jobs_deleted_at', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NOT NULL)')
        batch_op.create_index('idx_jobs_client_trgm', ['client'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_jobs_client_prefix', ['client'], unique=False, postgresql_where='(deleted_at IS NULL)')
        batch_op.create_index('idx_jobs_client_lower', [sa.literal_column('lower(client::text)')], unique=False)
        batch_op.create_index('idx_jobs_client_clean', [sa.literal_column("regexp_replace(lower(client::text), '[^a-z0-9 ]'::text, ' '::text, 'g'::text)")], unique=False)
        batch_op.create_index('idx_jobs_address_trgm', ['address'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_jobs_address_lower', [sa.literal_column('lower(address::text)')], unique=False)
        batch_op.create_index('idx_jobs_address_clean', [sa.literal_column("regexp_replace(lower(address::text), '[^a-z0-9 ]'::text, ' '::text, 'g'::text)")], unique=False)
        batch_op.create_index('idx_jobs_active_lookup', ['job_number'], unique=False, postgresql_where='(deleted_at IS NULL)')
        batch_op.create_index('idx_jobs_active_job_number', ['job_number'], unique=False, postgresql_where='(deleted_at IS NULL)')
        batch_op.create_index('idx_jobs_active_client', ['client'], unique=False, postgresql_where='(deleted_at IS NULL)')
        batch_op.create_index('idx_jobs_active_address', ['address'], unique=False, postgresql_where='(deleted_at IS NULL)')
        batch_op.alter_column('tags',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
        batch_op.alter_column('document_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fema_link',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('plat_link',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('prop_appr_link',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('long',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('lat',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('county',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('client',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('job_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('updated_at')

    op.create_table('field_work',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('work_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('total_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('crew', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('drone_card', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('document_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='field_work_job_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='field_work_pkey')
    )
    op.create_table('related_jobs',
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('related_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='related_jobs_job_id_fkey'),
    sa.ForeignKeyConstraint(['related_id'], ['jobs.id'], name='related_jobs_related_id_fkey'),
    sa.PrimaryKeyConstraint('job_id', 'related_id', name='related_jobs_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_ip', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('username', name='user_username_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('fieldwork')
    op.drop_table('users')
    # ### end Alembic commands ###
