"""add due_date to job

Revision ID: f3218a36154c
Revises: 4716c9223793
Create Date: 2025-12-31 16:45:26.461711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3218a36154c'
down_revision = '4716c9223793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_job_tags_composite'))
        batch_op.drop_index(batch_op.f('idx_job_tags_job_id'))
        batch_op.drop_index(batch_op.f('idx_job_tags_tag_id'))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.alter_column('job_number',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('client',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('county',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('lat',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('long',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('prop_appr_link',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('plat_link',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('fema_link',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('document_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_jobs_active_address'), postgresql_where='(deleted_at IS NULL)')
        batch_op.drop_index(batch_op.f('idx_jobs_active_client'), postgresql_where='(deleted_at IS NULL)')
        batch_op.drop_index(batch_op.f('idx_jobs_active_job_number'), postgresql_where='(deleted_at IS NULL)')
        batch_op.drop_index(batch_op.f('idx_jobs_active_lookup'), postgresql_where='(deleted_at IS NULL)')
        batch_op.drop_index(batch_op.f('idx_jobs_address_clean'))
        batch_op.drop_index(batch_op.f('idx_jobs_address_lower'))
        batch_op.drop_index(batch_op.f('idx_jobs_address_trgm'), postgresql_ops={'address': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_index(batch_op.f('idx_jobs_client_clean'))
        batch_op.drop_index(batch_op.f('idx_jobs_client_lower'))
        batch_op.drop_index(batch_op.f('idx_jobs_client_prefix'), postgresql_ops={'client': 'text_pattern_ops'}, postgresql_where='(deleted_at IS NULL)')
        batch_op.drop_index(batch_op.f('idx_jobs_client_trgm'), postgresql_ops={'client': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_index(batch_op.f('idx_jobs_created_at_desc'), postgresql_where='(deleted_at IS NULL)')
        batch_op.drop_index(batch_op.f('idx_jobs_deleted_at'), postgresql_where='(deleted_at IS NOT NULL)')
        batch_op.drop_index(batch_op.f('idx_jobs_deleted_lookup'))
        batch_op.drop_index(batch_op.f('idx_jobs_deleted_original_lookup'), postgresql_where='(deleted_at IS NOT NULL)')
        batch_op.drop_index(batch_op.f('idx_jobs_job_number_clean'))
        batch_op.drop_index(batch_op.f('idx_jobs_job_number_lower'))
        batch_op.drop_index(batch_op.f('idx_jobs_job_number_prefix'), postgresql_ops={'job_number': 'text_pattern_ops'}, postgresql_where='(deleted_at IS NULL)')
        batch_op.drop_index(batch_op.f('idx_jobs_job_number_trgm'), postgresql_ops={'job_number': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_index(batch_op.f('idx_jobs_original_job_number'), postgresql_where='(original_job_number IS NOT NULL)')
        batch_op.drop_index(batch_op.f('idx_jobs_search_composite'), postgresql_where='(deleted_at IS NULL)')
        batch_op.drop_index(batch_op.f('idx_jobs_status'), postgresql_where='(deleted_at IS NULL)')
        batch_op.drop_index(batch_op.f('idx_jobs_status_county'), postgresql_where='(deleted_at IS NULL)')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('pois', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('pois_created_at_idx'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_username'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_users_username'), ['username'], unique=False)

    with op.batch_alter_table('pois', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('pois_created_at_idx'), [sa.literal_column('created_at DESC')], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_jobs_status_county'), ['status', 'county'], unique=False, postgresql_where='(deleted_at IS NULL)')
        batch_op.create_index(batch_op.f('idx_jobs_status'), ['status'], unique=False, postgresql_where='(deleted_at IS NULL)')
        batch_op.create_index(batch_op.f('idx_jobs_search_composite'), ['deleted_at', 'status', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(deleted_at IS NULL)')
        batch_op.create_index(batch_op.f('idx_jobs_original_job_number'), ['original_job_number'], unique=False, postgresql_where='(original_job_number IS NOT NULL)')
        batch_op.create_index(batch_op.f('idx_jobs_job_number_trgm'), ['job_number'], unique=False, postgresql_ops={'job_number': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.create_index(batch_op.f('idx_jobs_job_number_prefix'), ['job_number'], unique=False, postgresql_ops={'job_number': 'text_pattern_ops'}, postgresql_where='(deleted_at IS NULL)')
        batch_op.create_index(batch_op.f('idx_jobs_job_number_lower'), [sa.literal_column('lower(job_number::text)')], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_job_number_clean'), [sa.literal_column("regexp_replace(lower(job_number::text), '[^a-z0-9]'::text, ''::text, 'g'::text)")], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_deleted_original_lookup'), ['original_job_number', 'deleted_at'], unique=False, postgresql_where='(deleted_at IS NOT NULL)')
        batch_op.create_index(batch_op.f('idx_jobs_deleted_lookup'), ['original_job_number', 'deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_deleted_at'), ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NOT NULL)')
        batch_op.create_index(batch_op.f('idx_jobs_created_at_desc'), [sa.literal_column('created_at DESC')], unique=False, postgresql_where='(deleted_at IS NULL)')
        batch_op.create_index(batch_op.f('idx_jobs_client_trgm'), ['client'], unique=False, postgresql_ops={'client': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.create_index(batch_op.f('idx_jobs_client_prefix'), ['client'], unique=False, postgresql_ops={'client': 'text_pattern_ops'}, postgresql_where='(deleted_at IS NULL)')
        batch_op.create_index(batch_op.f('idx_jobs_client_lower'), [sa.literal_column('lower(client::text)')], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_client_clean'), [sa.literal_column("regexp_replace(lower(client::text), '[^a-z0-9 ]'::text, ' '::text, 'g'::text)")], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_address_trgm'), ['address'], unique=False, postgresql_ops={'address': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.create_index(batch_op.f('idx_jobs_address_lower'), [sa.literal_column('lower(address::text)')], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_address_clean'), [sa.literal_column("regexp_replace(lower(address::text), '[^a-z0-9 ]'::text, ' '::text, 'g'::text)")], unique=False)
        batch_op.create_index(batch_op.f('idx_jobs_active_lookup'), ['job_number'], unique=False, postgresql_where='(deleted_at IS NULL)')
        batch_op.create_index(batch_op.f('idx_jobs_active_job_number'), ['job_number'], unique=False, postgresql_where='(deleted_at IS NULL)')
        batch_op.create_index(batch_op.f('idx_jobs_active_client'), ['client'], unique=False, postgresql_where='(deleted_at IS NULL)')
        batch_op.create_index(batch_op.f('idx_jobs_active_address'), ['address'], unique=False, postgresql_where='(deleted_at IS NULL)')
        batch_op.alter_column('document_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fema_link',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('plat_link',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('prop_appr_link',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('long',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('lat',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('county',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('client',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('job_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('due_date')

    with op.batch_alter_table('job_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_job_tags_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_job_tags_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_job_tags_composite'), ['job_id', 'tag_id'], unique=False)

    # ### end Alembic commands ###
