# @package dataset
name: universityA
# Dataset paths
root_dir : /Users/melocoton/Developer/niloc/data/universityA
train_list : /Users/melocoton/Developer/niloc/data/universityA/train.txt
val_list: /Users/melocoton/Developer/niloc/data/universityA/val.txt
test_list : /Users/melocoton/Developer/niloc/data/universityA/test.txt

