# @package _group_
name: universityA

# Dataset paths
root_dir: /home/anastasia/Desktop/Repos/niloc/niloc/data/universityA
train_list: /home/anastasia/Desktop/Repos/niloc/niloc/data/universityA/train.txt
val_list: /home/anastasia/Desktop/Repos/niloc/niloc/data/universityA/val.txt
test_list: /home/anastasia/Desktop/Repos/niloc/niloc/data/universityA/test.txt
