# @package _group_
name: avalon_synthetic
root_dir: /Users/melocoton/Developer/niloc-fork/niloc/data/avalon/synthetic_output
train_list: /Users/melocoton/Developer/niloc-fork/niloc/data/avalon/synthetic_output/train.txt
val_list: /Users/melocoton/Developer/niloc-fork/niloc/data/avalon/synthetic_output/val.txt
