# niloc/config/dataset/avalon_syn.yaml
name: avalon_synthetic
root_dir: /home/anastasia/Desktop/Repos/niloc/niloc/data/avalon/synthetic_output
train_list: /home/anastasia/Desktop/Repos/niloc/niloc/data/avalon/synthetic_output/train.txt
val_list: /home/anastasia/Desktop/Repos/niloc/niloc/data/avalon/synthetic_output/val.txt
