# @package dataset
name: universityB
# Dataset paths
root_dir : /Users/melocoton/Developer/niloc/data/universityB
train_list : /Users/melocoton/Developer/niloc/data/universityB/train.txt
val_list: /Users/melocoton/Developer/niloc/data/universityB/val.txt
test_list : /Users/melocoton/Developer/niloc/data/universityB/test.txt

