# @package dataset
name: officeC
# Dataset paths
root_dir : /Users/melocoton/Developer/niloc/data/officeC
train_list : /Users/melocoton/Developer/niloc/data/officeC/train.txt
val_list: /Users/melocoton/Developer/niloc/data/officeC/val.txt
test_list : /Users/melocoton/Developer/niloc/data/officeC/test.txt